### ISSUE TITLE
Bug: The Glyphery, Deep Pit: Occasional audio cut-out

### ISSUE THREAD

**Issue by wisprabbit** [erikh2000/gk1#13]
Reported by DannySpillerVA. Voice lines in The Glyphery may cut out, as demonstrated in Danny's clip: https://clips.twitch.tv/YummyScrumptiousGoshawkKappaRoss-WL2vy09wsxR-k9Kw

The song in Deep Pit may also cut out, as seen in another of Danny's streams.

This is related to a long-standing bug in GK development where sounds and music would cut out, which was tracked down to a bug in the Unity engine. Since the Unity bug can't be fixed, GK features a workaround in several places which restarts audio which has cut out. This workaround needs to be applied to The Glyphery, which features special logic for playing voices in its soundscape audio, and to Deep Pit's song controller.

**Comment by erikh2000** [comment]
Fixed in v1.1.
