### ISSUE TITLE
Bug: Some metal railings can be walked through

### ISSUE THREAD

**Issue by wisprabbit** [erikh2000/gk1#3]
Certain metal railings throughout the game are not solid, and Emm can pass through them.

Two known examples have been spotted by big al phillips. One in Facedral:
![metal-railings-1](https://user-images.githubusercontent.com/6506229/152773420-770b70b0-a6ad-40c2-bedc-a0cba4bbb258.jpg)

One in Quadrax:
![metal-railings-2](https://user-images.githubusercontent.com/6506229/152773469-a62b2949-3f86-4e13-b81e-830f5acc09ea.jpg)

**Comment by erikh2000** [comment]
Fixed in v1.1.
