### ISSUE TITLE
Feature request: Plundy Paths: not clear who's cooing excitedly

### ISSUE THREAD

**Issue by wisprabbit** [erikh2000/gk1#7]
Reported by big al phillips: when you rebirth a block to a correct spot in Plundy Paths, Plundy will coo. This dialogue activates Emm and Plundy's faces. But because Plundy is in the corner away from the correct blockpads, his face is usually off-screen, and only Emm's face is visible. This makes it appear that Emm is the one cooing excitedly. al suggests putting Plundy's head on screen to make it more obvious that Plundy is reacting.

**Comment by erikh2000** [comment]
Fixed in v1.1.
